export const sources=[
 {id:'frame',title:'Four Houses · первая очередь',url:'https://docs.google.com/presentation/d/1I1hrutPRMEI4D0gvxesG58pikb-hsoqS_FDNHVEQLHQ/edit',note:'Площадь и участок: слайд 4. Коммуникации: слайд 3. Спецификация: слайд 8.'},
 {id:'module',title:'Four Houses · модульные дома',url:'https://docs.google.com/presentation/d/13X8JF4P7HpeHSIXtRg3wsCFVMRoDgJQ7EoAEidpVyTM/edit',note:'Вторая очередь: слайды 2, 3, 7, 11. Планировки и визуализации из презентации.'},
 {id:'living',title:'Living Houses · третья очередь',url:'https://docs.google.com/presentation/d/1GdY3BZp2XpQPAE83pLuFRMa0R70K-z-WaHRhf3xlcA4/edit',note:'СИП-проект: слайды 2-7. Реальные фотографии первой и второй очереди: слайды 11-14, 19-21.'},
 {id:'elina',title:'Элина Чичкова · публичная страница',url:'https://taplink.cc/kupitnedorogo.sochi',note:'Имя и компания «Регион-Партнер». Публичные направления деятельности.'},
 {id:'channel',title:'Дома и строительство · канал Элины',url:'https://t.me/ElinaChichkova',note:'Текущие публичные направления: строительство, дома и участки. Контакт @elina_027 указан в канале.'}
];
export const types={frame:'Каркасные',module:'Модульные',sip:'СИП-панели'};
export const projects=[
 {id:'four-houses',name:'Four Houses',subtitle:'Дом с характером',edition:'Первая очередь',type:'frame',cover:'frameExterior',coverKind:'Фото проекта',area:'71 м²',plot:'4 сотки',address:'Верхнеармянское Лоо, пер. Дачный',water:'Центральная',electricity:'15 кВт на дом',sewage:'Локальные очистные',gas:'По границе',construction:'Деревянный каркас',description:'Панорамное остекление, деревянная отделка и собственный участок. В первой очереди Four Houses предусмотрены четыре каркасных дома на закрытой территории.',summary:'Свет, дерево и пространство для своего ритма.',features:['Деревянная внутренняя отделка','Своя мангальная зона','Парковочное место'],source:'frame',gallery:[{image:'frameExterior',label:'Дома первой очереди',kind:'Фотография'},{image:'frameAerial',label:'Расположение домов на территории',kind:'Фотография'},{image:'frameInterior',label:'Деревянная отделка и лестница',kind:'Фотография'},{image:'frameWindow',label:'Панорамное остекление',kind:'Фотография'}],plan:{image:'frameStructure',label:'Конструктивная схема',kind:'Схема из презентации'},note:'Площадь 71 м² и участок 4 сотки указаны в презентации первой очереди. Актуальное наличие, комплектация и стоимость не подтверждены.'},
 {id:'minibarn',name:'MiniBarn',subtitle:'Меньше лишнего. Больше воздуха.',edition:'Four Houses · вторая очередь',type:'module',cover:'moduleExterior',coverKind:'Фото строительства',area:'По запросу',dimensions:'9,2 × 4,36 м',plot:'от 4 соток',address:'Верхнеармянское Лоо, пер. Дачный',water:'Центральная',electricity:'Подключение предусмотрено',sewage:'Локальные очистные',gas:'По границе',construction:'Модульный дом',description:'Компактный модульный формат с террасой. Во второй очереди Four Houses представлены восемь домов в едином стиле на индивидуальных участках.',summary:'Модульный формат, открытая терраса, жизнь ближе к природе.',features:['Терраса','Модульная конструкция','Варианты планировки'],source:'module',gallery:[{image:'moduleExterior',label:'Возведение модульного дома',kind:'Фото строительства'},{image:'moduleTerrace',label:'Терраса модульного дома',kind:'Фотография'},{image:'moduleRender',label:'Архитектурный образ',kind:'Визуализация'},{image:'moduleInterior',label:'Дизайн гостиной',kind:'Визуализация'}],plan:{image:'modulePlan',label:'Вариант планировки MiniBarn',kind:'План из презентации'},note:'Габариты 9,2 × 4,36 м указаны в спецификации MiniBarn. Это не заявленная площадь дома. Наличие и текущая комплектация требуют уточнения.'},
 {id:'living-houses',name:'Living Houses',subtitle:'Пространство для жизни',edition:'Третья очередь',type:'sip',cover:'livingExterior',coverKind:'Визуализация',area:'По запросу',plot:'от 4 соток',address:'Верхнеармянское Лоо, ул. Краснооктябрьская',water:'Скважина',electricity:'На каждый дом',sewage:'Локальные очистные',gas:'По границе',construction:'СИП-панели',description:'Проект семи домов из СИП-панелей на закрытой территории. Открытая терраса и единый архитектурный стиль объединяют дома с окружающим ландшафтом.',summary:'Единый архитектурный стиль и собственная терраса.',features:['Закрытая территория','Участки от 4 соток','Планировка в презентации'],source:'living',gallery:[{image:'livingExterior',label:'Проект дома Living Houses',kind:'Визуализация'},{image:'livingTerrace',label:'Терраса и фасад',kind:'Визуализация'},{image:'livingInterior',label:'Дизайн-проект гостиной',kind:'Визуализация'},{image:'livingBedroom',label:'Дизайн-проект спальни',kind:'Визуализация'}],plan:{image:'livingPlan',label:'Планировка Living Houses',kind:'План из презентации'},note:'Фотографии построенного дома в этом разделе не заявляются. Показаны визуализации и план из публичной презентации. Площадь, готовность, наличие и цена требуют уточнения.'}
];
