const {chromium}=require('playwright');const {execFileSync}=require('node:child_process');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||execFileSync('which',['chromium'],{encoding:'utf8'}).trim(),headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];const sends=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))sends.push(r.url());});const root=process.env.DEMO_URL||'http://127.0.0.1:4173/';
try{
 await page.goto(root);await page.getByRole('heading',{name:'Свой дом. Свой ритм.'}).waitFor({timeout:5000});
 await page.getByRole('link',{name:'Смотреть проекты',exact:true}).first().click();assert.equal(await page.locator('[data-project-card]').count(),3);
 await page.getByRole('button',{name:'Модульные',exact:true}).click();assert.equal(await page.locator('[data-project-card]').count(),1);await page.getByRole('link',{name:'Подробнее о MiniBarn'}).click();await page.getByRole('heading',{name:'MiniBarn',exact:true}).waitFor();
 await page.getByRole('button',{name:'Открыть галерею'}).click();assert.equal(await page.locator('dialog[open]').count(),1);await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 await page.getByRole('button',{name:'Добавить MiniBarn к сравнению'}).click();await page.goto(root+'#/project/four-houses');await page.getByRole('button',{name:'Добавить Four Houses к сравнению'}).click();await page.goto(root+'#/compare');await page.getByRole('heading',{name:'Сравнить, чтобы выбрать.'}).waitFor();assert.equal(await page.locator('[data-compare-project]').count(),2);await page.reload();assert.equal(await page.locator('[data-compare-project]').count(),2);
 await page.goto(root+'#/project/four-houses');await page.getByRole('button',{name:'Сохранить Four Houses'}).click();await page.goto(root+'#/saved');assert.equal(await page.locator('[data-project-card]').count(),1);
 await page.goto(root+'#/request');await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByText('Выберите, для чего ищете дом',{exact:true}).waitFor();await page.getByLabel('Для постоянной жизни').check();await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByRole('button',{name:'Проверить запрос'}).click();await page.getByText('Как к вам обращаться?',{exact:true}).waitFor();await page.getByLabel('Ваше имя').fill('Тестовый посетитель');await page.getByLabel('Телефон, Telegram или email').fill('@demo_person');await page.getByLabel('Понимаю: это демо, данные никуда не отправляются').check();await page.getByRole('button',{name:'Проверить запрос'}).click();await page.getByRole('heading',{name:'Запрос готов.'}).waitFor();assert.equal(sends.length,0);const stored=await page.evaluate(()=>JSON.stringify(localStorage));assert(!stored.includes('Тестовый'));assert(!stored.includes('demo_person'));
 for(const route of ['#/about','#/sources','#/project/living-houses','#/does-not-exist']){await page.goto(root+route);assert(await page.locator('h1').textContent());}
 await context.newPage().then(async p=>{await p.goto(root);await p.locator('h1').waitFor();await p.evaluate(()=>{localStorage.setItem('rp.compare','{bad');localStorage.setItem('rp.saved','["invalid"]')});await p.goto(root+'#/compare');await p.reload();await p.getByText('Пока нечего сравнивать',{exact:true}).waitFor();await p.close();});
 await page.goto(root+'#/request');await page.getByLabel('Для постоянной жизни').check();await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByRole('button',{name:'Продолжить',exact:true}).click();await page.getByLabel('Ваше имя').fill('Не терять ввод');await page.getByLabel('Телефон, Telegram или email').fill('@keep_draft');const peer=await context.newPage();await peer.goto(root);await peer.locator('h1').waitFor();await peer.evaluate(()=>localStorage.setItem('rp.saved','["living-houses"]'));await page.getByRole('link',{name:'Избранное, 1'}).waitFor();await page.waitForTimeout(150);assert.equal(await page.getByLabel('Ваше имя').inputValue(),'Не терять ввод','other-tab selection must not erase form draft');await peer.close();
 await page.setViewportSize({width:390,height:844});await page.goto(root);await page.locator('h1').waitFor();assert(await page.locator('.header-cta').evaluate(e=>e.getBoundingClientRect().height)>=44,'mobile primary control is at least 44px');assert(await page.locator('.hero-copy>p').evaluate(e=>parseFloat(getComputedStyle(e).fontSize))>=13,'mobile hero copy readable');assert(await page.locator('.save-button').first().evaluate(e=>e.getBoundingClientRect().height)>=44,'save control is at least 44px');for(const route of ['#/','#/catalog','#/project/four-houses','#/compare','#/request','#/about','#/sources']){await page.goto(root+route);await page.locator('h1').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow: ${route}`);assert.equal(await page.locator('img').evaluateAll(els=>els.filter(x=>!x.complete||!x.naturalWidth).length),0,`images ${route}`);}
 assert.deepEqual(errors,[]);console.log('PASS: routes, filters, gallery, compare persistence, saved, form privacy, storage recovery, 390px and image health.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
